version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/mapper/create_cwadb.sql:/docker-entrypoint-initdb.d/create_cwadb.sql
    environment:
      MYSQL_DATABASE: "cwadb"
      MYSQL_ROOT_PASSWORD: "p@ssw0rd"

    restart: always
volumes:
  logvolume01: {}